version: '3.9'
services:
  koemi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: koemi-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped 