version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: koemi-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      # Router for Tailscale network
      - "traefik.http.routers.koemi-tailscale.rule=Host(`koemi.local`)"
      - "traefik.http.routers.koemi-tailscale.entrypoints=web,tailscale"
      - "traefik.http.services.koemi-tailscale.loadbalancer.server.port=3000"
      - "traefik.http.routers.koemi-tailscale.service=koemi-tailscale"
      # Keep the original port accessible
      - "traefik.http.routers.koemi-local.rule=Host(`localhost`)"
      - "traefik.http.routers.koemi-local.entrypoints=web"
      - "traefik.http.routers.koemi-local.service=koemi-tailscale"